### ISSUE TITLE
Growl Notifier for Google Play_Windows 64

### ISSUE THREAD

**Issue by Skypearl** [nickblt/cloudplayer-growler#2]
Hello.. a lot of computers works with CPU x64 ...
So ... your application doesn't run with some PC's...
I have Windows 8 64 bits ... and I can't install this extension...
:0)
(Sorry for my english .. i'm french)
Have a nice day,
Sébastien.

**Comment by nickblt** [comment]
Sorry, this doesn't support windows at all.
